sudo: false
language: python
cache: pip

python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - DJANGO=1.4
  - DJANGO=1.5
  - DJANGO=1.6
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.7
    - python: "3.3"
      env: DJANGO=1.4
    - python: "3.4"
      env: DJANGO=1.4

install:
  - pip install Django==$DJANGO
  - pip install mock pytest pytest-cov codecov

script:
  - "py.test --cov-report=term-missing --cov-report=xml --cov=django_zip_stream/ tests/"
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
